### ISSUE TITLE
Publish on Chef Supermarket

### ISSUE THREAD

**Issue by mansona** [Afterglow/chef-reboot#5]
I'm looking for a quick script to reboot a box for me and I noticed this repo isn't on Supermarket. There is only https://supermarket.getchef.com/cookbooks/reboot-handler

I like your one better because it seems simpler :+1:

**Comment by danhper** [comment]
I was having problem using this as a dependency for a 
[cookbook of mine](https://github.com/tuvistavie/tomoyo-chef), so
I took the freedom to publish your cookbook to the supermarket.
If you want me to delete it, please let me know at any time.
My email is available on my profile page.

**Comment by Afterglow** [comment]
no problem, guess I can close this if its now available on the supermarket :)
